from enum import Enum

poses = [
    "IDLE",
    "ANGRY_HANDS_ON_WAIST",
    "ANGRY_FISTS_FRONT",
    "BRAVE_HAND_ON_CHEST",
    "CALM_HANDS_ON_BACK",
    "CALM_HANDS_ON_FRONT",
    "CAT",
    "CLASSY_LEFT_HAND_ON_WAIST",
    "CONCERN_RIGHT_HAND_ON_FRONT",
    "CRY",
    "CUTE_HANDS_ON_FRONT",
    "CUTE_HANDS_STICK_OUT",
    "CUTE_LEANING_FORWARD",
    "DENY",
    "ENERGETIC_RIGHT_FIST_UP",
    "ENERGETIC_RIGHT_HAND_PEACE",
    "ENERGETIC_FLEX",
    "FED_UP_SLOUCHING",
    "FED_UP_RIGHT_HAND_ON_FACE",
    "LAUGH",
    "PITIABLE_RIGHT_HAND_ON_BACK_HEAD",
    "POINT_FINGER",
    "SEXY_RIGHT_HAND_POINTY_FINGER",
    "SEXY_POSE",
    "SEXY_LEAN_FORWARD",
    "STRESS_HANDS_ON_BACK_HEAD",
    "SURPRISE_HANDS_OPEN_FRONT",
    "THINK",
    "SHRUG"
    "LAUGH_DOWN",
    "LAUGH_UP",
    "NOD_ONCE",
    "NOD_TWICE",
    "SHAKE_BODY",
    "SHAKE_HEAD",
    "TILT_NECK",
    "CUTE"
    "ENERGETIC",
    "WAVE_ARM",
    "WAVE_HANDS",
    "WAVE_HAND",
    "DOGEZA_1",
    "DOGEZA_2",
    "W-SITTING",
    "SEIZA"

]

class Poses(str, Enum):
    IDLE = "IDLE"
    ANGRY_HANDS_ON_WAIST = "ANGRY_HANDS_ON_WAIST"
    ANGRY_FISTS_FRONT = "ANGRY_FISTS_FRONT"
    BRAVE_HAND_ON_CHEST = "BRAVE_HAND_ON_CHEST"
    CALM_HANDS_ON_BACK = "CALM_HANDS_ON_BACK"
    CALM_HANDS_ON_FRONT = "CALM_HANDS_ON_FRONT"
    CAT = "CAT"
    CLASSY_LEFT_HAND_ON_WAIST = "CLASSY_LEFT_HAND_ON_WAIST"
    CONCERN_RIGHT_HAND_ON_FRONT = "CONCERN_RIGHT_HAND_ON_FRONT"
    CRY = "CRY"
    CUTE_HANDS_ON_FRONT = "CUTE_HANDS_ON_FRONT"
    CUTE_HANDS_STICK_OUT = "CUTE_HANDS_STICK_OUT"
    CUTE_LEANING_FORWARD = "CUTE_LEANING_FORWARD"
    DENY = "DENY"
    ENERGETIC_RIGHT_FIST_UP = "ENERGETIC_RIGHT_FIST_UP"
    ENERGETIC_RIGHT_HAND_PEACE = "ENERGETIC_RIGHT_HAND_PEACE"
    ENERGETIC_FLEX = "ENERGETIC_FLEX"
    FED_UP_SLOUCHING = "FED_UP_SLOUCHING"
    FED_UP_RIGHT_HAND_ON_FACE = "FED_UP_RIGHT_HAND_ON_FACE"
    LAUGH = "LAUGH"
    PITIABLE_RIGHT_HAND_ON_BACK_HEAD = "PITIABLE_RIGHT_HAND_ON_BACK_HEAD"
    POINT_FINGER = "POINT_FINGER"
    SEXY_RIGHT_HAND_POINTY_FINGER = "SEXY_RIGHT_HAND_POINTY_FINGER"
    SEXY_POSE = "SEXY_POSE"
    SEXY_LEAN_FORWARD = "SEXY_LEAN_FORWARD"
    STRESS_HANDS_ON_BACK_HEAD = "STRESS_HANDS_ON_BACK_HEAD"
    SURPRISE_HANDS_OPEN_FRONT = "SURPRISE_HANDS_OPEN_FRONT"
    THINK = "THINK"
    SHRUG = "SHRUG"
    LAUGH_DOWN = "LAUGH_DOWN"
    LAUGH_UP = "LAUGH_UP"
    NOD_ONCE = "NOD_ONCE"
    NOD_TWICE = "NOD_TWICE"
    SHAKE_BODY = "SHAKE_BODY"
    SHAKE_HEAD = "SHAKE_HEAD"
    TILT_NECK = "TILT_NECK"
    CUTE = "CUTE"
    ENERGETIC = "ENERGETIC"
    WAVE_ARM = "WAVE_ARM"
    WAVE_HANDS = "WAVE_HANDS"
    WAVE_HAND = "WAVE_HAND"
    DOGEZA_1 = "DOGEZA_1"
    DOGEZA_2 = "DOGEZA_2"
    W_SITTING = "W-SITTING"
    SEIZA = "SEIZA"